# Matrix Algebra

## Eigenvalues

### Physical Example: 

A mass attached to a spring, behaves like Harmonic Oscillator (HO), whose energy is $U = \frac{1}{2}kx^2$. Where $k$ is the spring constant, and can be calculated $F = -\frac{\partial U}{\partial x} = -kx$. Using $F = ma = m\frac{d^2 x}{dx^2}$ one arrives at the $\omega = \sqrt{\frac{k}{m}}$


Assume vibrations of atoms: these imply multiple springs and multiple masses, interconnected. The characterstic (resoant) frequencies in molecular vibrations is closely realted to the eigenvalues.

eigenvalues of a matric can be calculated" `numpy.linalg.eigvals()`

In [4]:
import numpy as np
Matrix_Energy = np.array([[1,-1,0],[1,1.5,-0.5],[0,0.5,2]], float)
Eigen_values = np.linalg.eigvals(Matrix_Energy)
print("\nThe eigenvalues ($\lambda$) of the Matrix_Energy are")
print(f"={Eigen_values}")


The eigenvalues ($\lambda$) of the Matrix_Energy are
=[1.33160174+1.04166882j 1.33160174-1.04166882j 1.83679653+0.j        ]


Given the matrix $\mathrm{Matrix Energy} =  \begin{pmatrix}1 & -1 & 0\\
1 & 1.5 & -.5\\
0 & 0.5 & 2\end{pmatrix}$


Rounded Real Eigenvalues are $\mathrm{ Real Eigenvalues} =\lambda_j=  \begin{pmatrix}1\\
1\\
2\end{pmatrix}$

and Rounded Imaginary $\mathrm{ Imaginary Eigenvalues} =\lambda_j=  \begin{pmatrix}1 \\
-1\\
0\end{pmatrix}$

The resonant frequencies are known as eigenfrequencies $\omega_j$ of your oscillations, and ther are related with the eigenvalues as $\lambda_j=\frac{m\omega_j^2}{k}$, so then it follows that $\omega_j=\sqrt{\frac{\lambda_jk}{m}}$, which is $\omega_j =\sqrt{\frac{k}{m}}  \begin{pmatrix}1 \\
-1\\
0\end{pmatrix}$

In a scenario where $m=1=k$, so then $\omega_j=\sqrt{\lambda}$

In [5]:
eigenvalues = np.array([1,1,2])
omega = np.sqrt(eigenvalues) 

In [6]:
print("\nThe eigenfrequencies ($\omega$) are")
print(f"={omega}")


The eigenfrequencies ($\omega$) are
=[1.         1.         1.41421356]


# Singular Value Decomposition (SVD

Decomposes a matrix, matrix $H$ as follows

$H = U\mathrm{diag}(\omega_j)V^T$ where the propoerties $U^TU=UU^T=1$ and $V^TV=VV^T=1$. Note that $U, V$ are orthogonal matricex and $\omega_j$ are the singularf values arranhed diagonally. Meaning $\Omega = diag(\omega_j)$.

If the inverse exists, you can calculate it via SVD as $H^{-1} = V\mathrm{diag}(\frac{1}{\omega_j})U^T$ 


Application: solving $Ax=b$ written in matrix form as follows $ \begin{pmatrix}a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\end{pmatrix}\times\begin{pmatrix}x_1 \\
x_2\\
x_3\end{pmatrix}=\begin{pmatrix}b_1 \\
b_2\\
b_3\end{pmatrix}$

In [21]:
A = np.array([[1,2,3],[4,5,6],[-1,2,-1]])
b = np.array([0,1,2])

In [22]:
np.linalg.solve(A,b)

array([ 0.11111111,  0.77777778, -0.55555556])

Using the SVD $x=A^{-1}b$ , lets call $O= \Omega = diag(\omega_j)$.

In [24]:
U,O, VT = np.linalg.svd(A)

print(O)

[9.508032   2.44948974 0.77286964]


SVD check? $A = U\mathrm{diag}(\omega_j)V^T$ 

In [25]:
U.dot(np.diag(O).dot(VT))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [-1.,  2., -1.]])

In [26]:
np.allclose(A,U.dot(np.diag(O).dot(VT)))

True

In [27]:
inverse_O = 1/O
print(inverse_O)

[0.10517424 0.40824829 1.29387927]


In [29]:
A_inverse = VT.T.dot(np.diag(inverse_O)).dot(U.T) 
print(A_inverse)

[[-0.94444444  0.44444444 -0.16666667]
 [-0.11111111  0.11111111  0.33333333]
 [ 0.72222222 -0.22222222 -0.16666667]]


In [30]:
np.allclose(A_inverse ,np.linalg.inv(A))

True

In [32]:
x = A_inverse.dot(b)
print(x)
np.allclose(x,np.linalg.solve(A,b))

[ 0.11111111  0.77777778 -0.55555556]


True

In [33]:
A.dot(x)

array([-1.33226763e-15,  1.00000000e+00,  2.00000000e+00])

In [34]:
np.allclose(A.dot(x),b)

True

# Singular Matrix