# Matrix Algebra

## Singular Matrix

This is a matrix When you have matrix with no unique solution.

In [16]:
import numpy as np
Matrix_Singular = np.array([[1,-1,0],[1,1.5,-0.5],[1,1.5,-0.5]], float)
b1= np.array([2.3,-0.3, -0.3])
b2= np.array([0,1, 1])

In [17]:
np.linalg.solve(Matrix_Singular, b1 )

LinAlgError: Singular matrix

In [18]:
np.linalg.solve(Matrix_Singular, b2 )

LinAlgError: Singular matrix

### Let us consider the scenario

$Dx=b_1$

In [19]:
D = Matrix_Singular.copy()
D[2,:] = Matrix_Singular[0]-4*Matrix_Singular[1]

In [20]:
np.linalg.solve(D, b1 )

array([6.84547143e+15, 6.84547143e+15, 3.42273572e+16])

In [21]:
np.linalg.solve(D, b2 )

array([-9.00719925e+15, -9.00719925e+15, -4.50359963e+16])

# These values are huge, so caution must be taken. It is an indication of singular matrix.

# USing SVD for Singualr Matrix

Using the SVD $x=A^{-1}b$ , lets call $O= \Omega = diag(\omega_j)$.

What we are computing is a pseudo-inverse $A^{-1} = V diag(\beta_j)U^T$ in this case notice that $\beta_j = \frac{1}{\omega_j}~~~~  \mathrm{if}~~~~   \omega_j~~~~ \neq 0, ~~~~\frac{1}{\omega_j}  = 0,~~~~ \mathrm{if} ~~~~\omega_j=0$

In [22]:
A = np.array([[1,2,3],[4,5,6],[-1,2,-1]])
b = np.array([0,1,2])
U,O, VT = np.linalg.svd(A)

print(O)

[9.508032   2.44948974 0.77286964]


In [23]:
U,W, VT = np.linalg.svd(Matrix_Singular)

print(W)

[2.66422150e+00 1.37910253e+00 8.31562269e-17]


Note here that, the third value is almost zero $\omega_2\approx 0$, an indication of singular matrix.

SVD check? $A = U\mathrm{diag}(\omega_j)V^T$ 

In [24]:
U.dot(np.diag(W).dot(VT))

array([[ 1.00000000e+00, -1.00000000e+00,  1.11022302e-16],
       [ 1.00000000e+00,  1.50000000e+00, -5.00000000e-01],
       [ 1.00000000e+00,  1.50000000e+00, -5.00000000e-01]])

In [25]:
np.allclose(Matrix_Singular,U.dot(np.diag(W).dot(VT)))

True